// vehicletracking-frontend/src/components/operations/ConfirmStationDelete.tsx
import { useEffect, useRef } from 'react';
import type { Station } from '../../types/station';

export function ConfirmStationDelete({ station, saving, onCancel, onConfirm }: {
  station: Station; saving: boolean; onCancel: () => void; onConfirm: () => void;
}) {
  const dialogRef = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = dialogRef.current; dialog?.showModal(); return () => dialog?.close(); }, []);
  return <dialog ref={dialogRef} className="confirmation-dialog" aria-labelledby="deactivate-title" onCancel={event => { event.preventDefault(); if (!saving) onCancel(); }}>
    <div className="dialog-icon" aria-hidden="true">!</div>
    <h2 id="deactivate-title">Ngừng sử dụng trạm?</h2>
    <div className="dialog-station-info"><strong>{station.name}</strong><p>{station.address}</p></div>
    <p className="dialog-explanation">Trạm sẽ không được dùng cho tuyến mới. Dữ liệu lịch sử vẫn được lưu trữ.</p>
    <div className="dialog-actions"><button className="secondary-action" onClick={onCancel} disabled={saving} autoFocus>Hủy bỏ</button><button className="danger-action" onClick={onConfirm} disabled={saving}>{saving ? 'Đang xử lý…' : 'Xác nhận ngừng sử dụng'}</button></div>
  </dialog>;
}

// vehicletracking-frontend/src/features/stations/components/ConfirmStationDelete.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, shallowRef } from 'vue';
import type { Station } from '@/features/stations/types/station';
defineProps<{ station: Station; saving: boolean; onCancel: () => void; onConfirm: () => void }>();
const dialog = shallowRef<HTMLDialogElement | null>(null);
onMounted(() => dialog.value?.showModal());
onBeforeUnmount(() => dialog.value?.close());
</script>
<template>
  <dialog
    ref="dialog"
    class="confirmation-dialog"
    aria-labelledby="deactivate-title"
    @cancel.prevent="!saving && onCancel()"
  >
    <div
      class="dialog-icon"
      aria-hidden="true"
    >
      !
    </div>
    <h2 id="deactivate-title">Ngừng sử dụng trạm?</h2>
    <div class="dialog-station-info">
      <strong>{{ station.name }}</strong>
      <p>{{ station.address }}</p>
    </div>
    <p class="dialog-explanation">
      Trạm sẽ không được dùng cho tuyến mới. Dữ liệu lịch sử vẫn được lưu trữ.
    </p>
    <div class="dialog-actions">
      <button
        class="secondary-action"
        :disabled="saving"
        autofocus
        @click="onCancel"
      >
        Hủy bỏ</button
      ><button
        class="danger-action"
        :disabled="saving"
        @click="onConfirm"
      >
        {{ saving ? 'Đang xử lý…' : 'Xác nhận ngừng sử dụng' }}
      </button>
    </div>
  </dialog>
</template>
