// vehicletracking-frontend/src/features/fleet/components/FleetWorkspace.vue
<script setup lang="ts">
import { computed, ref, shallowRef } from 'vue';
import {
  ArrowRight,
  BusFront,
  CalendarDays,
  CarFront,
  CheckCircle2,
  Edit3,
  Plus,
  RefreshCw,
  Scooter,
  Search,
  Trash2,
  UserRound,
} from '@lucide/vue';
import {
  TRIP_STATUS_LABELS,
  vehicleTypeLabel,
  type Driver,
  type DriverInput,
  type FleetVehicle,
  type TripDetail,
  type TripStatus,
  type VehicleInput,
} from '@/features/fleet/types/fleet';
import { useFleetWorkspace, type FleetTab } from '@/features/fleet/composables/useFleetWorkspace';
import { displayTripTime } from '@/features/fleet/utils/tripTime';
import VehicleEditor from './VehicleEditor.vue';
import TripEditor from './TripEditor.vue';
import TripDetailPanel from './TripDetailPanel.vue';
import FleetConfirmDialog from './FleetConfirmDialog.vue';
import DriverEditor from './DriverEditor.vue';
import FleetManagementTable from './FleetManagementTable.vue';
import type { OperationsSnapshot } from '@/features/tracking/types/operations';
import '@/features/fleet/styles/fleet.css';
const props = withDefaults(
  defineProps<{
    onToast: (message: string) => void;
    onFocusStop: (position: [number, number], zoom?: number) => void;
    onManageRoutes: () => void;
    onManageStations: () => void;
    liveSnapshot?: OperationsSnapshot | null;
    onSimulateTrip?: (id: number) => void;
    onFocusVehicle?: (id: number) => void;
    tripSelection?: { tripId: number | null } | null;
    onTripCreated?: (detail: TripDetail) => void;
    initialTab?: FleetTab;
    initialVehicleFilter?: number | null;
    lockedTab?: FleetTab;
    onViewVehicleTrips?: (vehicleId: number) => void;
    onClearVehicleFilter?: () => void;
  }>(),
  { initialTab: 'vehicles', initialVehicleFilter: null },
);
const fleet = useFleetWorkspace(
  (message) => props.onToast(message),
  () => props.liveSnapshot ?? null,
  () => props.tripSelection ?? null,
  (detail) => props.onTripCreated?.(detail),
  props.initialTab,
  props.initialVehicleFilter,
);
const activeTab = computed(() => props.lockedTab ?? fleet.tab),
  screen = computed(() => fleet.screen);
const query = ref(''),
  vehicleStatus = ref<'active' | 'inactive' | 'all'>('active'),
  driverStatus = ref<'active' | 'inactive' | 'all'>('active'),
  tripStatus = ref<TripStatus | ''>('');
const deactivate = shallowRef<FleetVehicle | null>(null),
  deactivateDriver = shallowRef<Driver | null>(null);
const q = computed(() => query.value.trim().toLocaleLowerCase('vi'));
const vehicles = computed(() =>
  fleet.vehicles.filter(
    (vehicle) =>
      (vehicleStatus.value === 'all' || vehicle.active === (vehicleStatus.value === 'active')) &&
      (!q.value ||
        `${vehicle.plateNumber} ${vehicle.name} ${vehicle.driver?.fullName ?? ''}`
          .toLocaleLowerCase('vi')
          .includes(q.value)),
  ),
);
const drivers = computed(() =>
  fleet.drivers.filter(
    (driver) =>
      (driverStatus.value === 'all' || driver.active === (driverStatus.value === 'active')) &&
      (!q.value ||
        `${driver.fullName} ${driver.phoneNumber} ${driver.licenseNumber}`
          .toLocaleLowerCase('vi')
          .includes(q.value)),
  ),
);
const trips = computed(() =>
  fleet.trips.filter(
    (trip) =>
      (!fleet.vehicleFilter || trip.vehicleId === fleet.vehicleFilter) &&
      (!tripStatus.value || trip.status === tripStatus.value) &&
      (!q.value ||
        `${trip.id} ${trip.vehiclePlateNumber} ${trip.routeName}`
          .toLocaleLowerCase('vi')
          .includes(q.value)),
  ),
);
const filteredVehicle = computed(() =>
  fleet.vehicles.find((vehicle) => vehicle.id === fleet.vehicleFilter),
);
const hasFilters = computed(() =>
  Boolean(
    query.value.trim() ||
    (activeTab.value === 'vehicles' && vehicleStatus.value !== 'active') ||
    (activeTab.value === 'drivers' && driverStatus.value !== 'active') ||
    (activeTab.value === 'trips' && (tripStatus.value || fleet.vehicleFilter)),
  ),
);
function clearVehicleFilter() {
  fleet.setVehicleFilter(null);
  if (activeTab.value === 'trips') props.onClearVehicleFilter?.();
}
function clearFilters() {
  query.value = '';
  vehicleStatus.value = 'active';
  driverStatus.value = 'active';
  tripStatus.value = '';
  clearVehicleFilter();
}
const moduleCopy = computed(() =>
  activeTab.value === 'vehicles'
    ? {
        eyebrow: 'ĐỘI XE',
        title: 'Phương tiện',
        description: 'Quản lý danh mục xe, trạng thái sử dụng và phân công hiện tại.',
        icon: BusFront,
        primary: 'Thêm phương tiện',
        total: fleet.vehicles.length,
        primaryAction: () => fleet.openVehicleForm(null),
      }
    : activeTab.value === 'drivers'
      ? {
          eyebrow: 'NHÂN SỰ VẬN HÀNH',
          title: 'Tài xế',
          description: 'Theo dõi hồ sơ, giấy phép và xe đang được phân công.',
          icon: UserRound,
          primary: 'Thêm tài xế',
          total: fleet.drivers.length,
          primaryAction: () => fleet.openDriverForm(null),
        }
      : {
          eyebrow: 'LỊCH VẬN HÀNH',
          title: 'Chuyến đi',
          description: 'Lập chuyến, phân công và theo dõi vòng đời vận hành.',
          icon: CalendarDays,
          primary: 'Tạo chuyến đi',
          total: fleet.trips.length,
          primaryAction: fleet.openTripForm,
        },
);
const activeCount = computed(() =>
  activeTab.value === 'vehicles'
    ? fleet.vehicles.filter((vehicle) => vehicle.active).length
    : activeTab.value === 'drivers'
      ? fleet.drivers.filter((driver) => driver.active).length
      : fleet.trips.filter((trip) => trip.status === 'IN_PROGRESS').length,
);
const activeLabel = computed(() =>
  activeTab.value === 'vehicles'
    ? 'đang sử dụng'
    : activeTab.value === 'drivers'
      ? 'đang hoạt động'
      : 'đang chạy',
);
const filteredCount = computed(() =>
  activeTab.value === 'vehicles'
    ? vehicles.value.length
    : activeTab.value === 'drivers'
      ? drivers.value.length
      : trips.value.length,
);
const hasActiveVehicle = computed(() => fleet.vehicles.some((vehicle) => vehicle.active));
const primaryDisabled = computed(
  () => fleet.loading || !!fleet.error || (activeTab.value === 'trips' && !hasActiveVehicle.value),
);
function viewVehicleTrips(id: number) {
  query.value = '';
  if (props.onViewVehicleTrips) props.onViewVehicleTrips(id);
  else fleet.showVehicleTrips(id);
}
const assignedVehicle = (id: number) =>
  fleet.vehicles.find((vehicle) => vehicle.active && vehicle.driver?.id === id);
const assignedVehicleLabel = (id: number) => {
  const v = assignedVehicle(id);
  return v ? `${v.plateNumber} · ${v.name}` : 'Chưa gán';
};
async function saveVehicle(input: VehicleInput, id?: number) {
  const saved = await fleet.saveVehicle(input, id);
  if (saved) {
    query.value = '';
    vehicleStatus.value = 'active';
  }
  return saved;
}
async function saveDriver(input: DriverInput, id?: number) {
  const saved = await fleet.saveDriver(input, id);
  if (saved) {
    query.value = '';
    driverStatus.value = 'active';
  }
  return saved;
}
function retryTrip() {
  if (screen.value.kind === 'trip-detail') void fleet.selectTrip(screen.value.id);
}
async function removeVehicle() {
  if (deactivate.value && (await fleet.removeVehicle(deactivate.value))) deactivate.value = null;
}
async function removeDriver() {
  if (deactivateDriver.value && (await fleet.removeDriver(deactivateDriver.value)))
    deactivateDriver.value = null;
}
</script>
<template>
  <div class="fleet-workspace">
    <div
      class="fleet-list-view"
      :hidden="screen.kind !== 'list'"
    >
      <header class="fleet-module-header">
        <div class="fleet-module-title">
          <span class="fleet-module-icon"
            ><component
              :is="moduleCopy.icon"
              :size="21"
          /></span>
          <div>
            <span class="fleet-module-eyebrow">{{ moduleCopy.eyebrow }}</span>
            <h2>{{ moduleCopy.title }}</h2>
            <p>{{ moduleCopy.description }}</p>
          </div>
        </div>
        <div class="fleet-module-summary">
          <div>
            <strong>{{ activeCount }}</strong
            ><span>{{ activeLabel }}</span>
          </div>
          <div>
            <strong>{{ moduleCopy.total }}</strong
            ><span>tổng danh mục</span>
          </div>
        </div>
        <div class="fleet-module-actions">
          <button
            class="fleet-refresh-button"
            :disabled="fleet.loading || fleet.busy"
            :aria-label="`Tải lại ${moduleCopy.title.toLocaleLowerCase('vi')}`"
            @click="fleet.reload"
          >
            <RefreshCw :size="16" /></button
          ><button
            class="fleet-primary-action"
            :disabled="primaryDisabled"
            :title="
              activeTab === 'trips' && !hasActiveVehicle
                ? 'Cần có ít nhất một xe đang sử dụng'
                : undefined
            "
            @click="moduleCopy.primaryAction"
          >
            <Plus :size="16" />{{ moduleCopy.primary }}
          </button>
        </div>
      </header>
      <div
        v-if="!lockedTab"
        class="planning-tabs fleet-tabs"
        aria-label="Quản lý đội xe"
      >
        <button
          :aria-pressed="activeTab === 'vehicles'"
          @click="
            fleet.setTab('vehicles');
            query = '';
          "
        >
          <BusFront :size="14" />Đội xe
          <span>{{ fleet.vehicles.filter((vehicle) => vehicle.active).length }}</span></button
        ><button
          :aria-pressed="activeTab === 'drivers'"
          @click="
            fleet.setTab('drivers');
            query = '';
          "
        >
          <UserRound :size="14" />Tài xế
          <span>{{ fleet.drivers.filter((driver) => driver.active).length }}</span></button
        ><button
          :aria-pressed="activeTab === 'trips'"
          @click="
            fleet.setTab('trips');
            query = '';
          "
        >
          <CalendarDays :size="14" />Chuyến đi <span>{{ fleet.trips.length }}</span>
        </button>
      </div>
      <div class="fleet-heading">
        <div>
          <span class="panel-eyebrow">DANH SÁCH HIỂN THỊ</span>
          <h2>{{ filteredCount }} kết quả{{ hasFilters ? ' phù hợp' : '' }}</h2>
        </div>
        <span class="fleet-list-hint"><CheckCircle2 :size="14" /> Dữ liệu hiện tại</span>
      </div>
      <div class="fleet-list-tools">
        <label class="fleet-search"
          ><Search :size="15" /><input
            v-model="query"
            :aria-label="
              activeTab === 'vehicles'
                ? 'Tìm xe'
                : activeTab === 'drivers'
                  ? 'Tìm tài xế'
                  : 'Tìm chuyến đi'
            "
            :placeholder="
              activeTab === 'vehicles'
                ? 'Biển số, tên xe hoặc tài xế…'
                : activeTab === 'drivers'
                  ? 'Tên, điện thoại hoặc GPLX…'
                  : 'Biển số, tuyến hoặc mã chuyến…'
            " /></label
        ><select
          v-if="activeTab === 'vehicles'"
          v-model="vehicleStatus"
          aria-label="Lọc xe"
        >
          <option value="active">Đang sử dụng</option>
          <option value="inactive">Đã ngừng sử dụng</option>
          <option value="all">Tất cả xe</option></select
        ><select
          v-else-if="activeTab === 'drivers'"
          v-model="driverStatus"
          aria-label="Lọc tài xế"
        >
          <option value="active">Đang hoạt động</option>
          <option value="inactive">Đã ngừng hoạt động</option>
          <option value="all">Tất cả tài xế</option></select
        ><template v-else
          ><select
            v-model="tripStatus"
            aria-label="Lọc trạng thái chuyến"
          >
            <option value="">Mọi trạng thái</option>
            <option
              v-for="(label, id) in TRIP_STATUS_LABELS"
              :key="id"
              :value="id"
            >
              {{ label }}
            </option>
          </select>
          <div
            v-if="fleet.vehicleFilter"
            class="fleet-filter-chip"
          >
            <span>Xe {{ filteredVehicle?.plateNumber ?? fleet.vehicleFilter }}</span
            ><button @click="clearVehicleFilter">Bỏ lọc xe</button>
          </div></template
        ><button
          v-if="hasFilters"
          class="fleet-clear-filters"
          @click="clearFilters"
        >
          Xóa bộ lọc
        </button>
      </div>
      <div
        class="fleet-list-body"
        :aria-busy="fleet.loading"
      >
        <p
          v-if="fleet.loading"
          class="fleet-loading"
          role="status"
        >
          Đang tải xe và chuyến đi…
        </p>
        <div
          v-if="fleet.error && !deactivate && !deactivateDriver"
          class="fleet-error"
          role="alert"
        >
          {{ fleet.error
          }}<button
            class="fleet-text-button"
            @click="fleet.reload"
          >
            Thử lại
          </button>
        </div>
        <FleetManagementTable
          v-if="!fleet.loading && !fleet.error && lockedTab"
          :tab="activeTab"
          :vehicles="vehicles"
          :all-vehicles="fleet.vehicles"
          :drivers="drivers"
          :trips="trips"
          :on-edit-vehicle="fleet.openVehicleForm"
          :on-deactivate-vehicle="(vehicle) => (deactivate = vehicle)"
          :on-vehicle-trips="viewVehicleTrips"
          :on-edit-driver="fleet.openDriverForm"
          :on-deactivate-driver="(driver) => (deactivateDriver = driver)"
          :on-trip="fleet.selectTrip"
        />
        <template v-if="!lockedTab && !fleet.loading && !fleet.error && activeTab === 'vehicles'">
          <div
            v-if="vehicles.length === 0"
            class="fleet-empty"
          >
            <BusFront :size="30" />
            <h3>
              {{
                fleet.vehicles.length ? 'Không tìm thấy xe phù hợp' : 'Chưa có xe trong danh mục'
              }}
            </h3>
            <p>Thêm xe, sau đó tạo chuyến từ tuyến đã lưu.</p>
            <button
              class="fleet-text-button"
              @click="onManageStations"
            >
              Thiết lập trạm
            </button>
          </div>
          <article
            v-for="vehicle in vehicles"
            :key="vehicle.id"
            class="fleet-vehicle-card"
          >
            <div class="fleet-card-main">
              <button
                class="fleet-vehicle-select"
                @click="viewVehicleTrips(vehicle.id)"
              >
                <span class="fleet-plate"
                  ><Scooter
                    v-if="vehicle.vehicleType === 'MOTORCYCLE'"
                    :size="16"
                  /><CarFront
                    v-else
                    :size="16"
                  />{{ vehicle.plateNumber }}</span
                ><strong>{{ vehicle.name }}</strong
                ><span class="fleet-help"
                  >{{ vehicleTypeLabel(vehicle.vehicleType) }} ·
                  {{ vehicle.active ? 'Đang sử dụng' : 'Đã ngừng sử dụng' }} ·
                  {{
                    liveSnapshot == null
                      ? 'Realtime xem tại Giám sát trực tiếp'
                      : liveSnapshot.positions.some((point) => point.vehicleId === vehicle.id)
                        ? 'Đã nhận vị trí'
                        : 'Chưa có vị trí xe'
                  }}</span
                ><span class="fleet-help"
                  >Tài xế: {{ vehicle.driver?.fullName ?? 'Chưa gán' }}</span
                >
              </button>
              <div
                v-if="vehicle.active"
                class="fleet-card-actions"
              >
                <button
                  class="fleet-icon-button"
                  :aria-label="`Sửa xe ${vehicle.plateNumber}`"
                  @click="fleet.openVehicleForm(vehicle)"
                >
                  <Edit3 :size="15" /></button
                ><button
                  class="fleet-icon-button danger"
                  :aria-label="`Ngừng sử dụng xe ${vehicle.plateNumber}`"
                  @click="deactivate = vehicle"
                >
                  <Trash2 :size="15" />
                </button>
              </div>
            </div>
            <p
              v-if="vehicle.description"
              class="fleet-card-description"
            >
              {{ vehicle.description }}
            </p>
            <button
              v-if="liveSnapshot?.positions.some((point) => point.vehicleId === vehicle.id)"
              class="fleet-text-button"
              @click="onFocusVehicle?.(vehicle.id)"
            >
              Xem vị trí xe</button
            ><button
              class="fleet-text-button"
              @click="viewVehicleTrips(vehicle.id)"
            >
              Xem chuyến đi <span>→</span>
            </button>
          </article>
        </template>
        <template v-if="!lockedTab && !fleet.loading && !fleet.error && activeTab === 'drivers'"
          ><div
            v-if="drivers.length === 0"
            class="fleet-empty"
          >
            <UserRound :size="30" />
            <h3>{{ fleet.drivers.length ? 'Không tìm thấy tài xế phù hợp' : 'Chưa có tài xế' }}</h3>
            <p>Thêm tài xế để phân công cho xe và chuyến đi.</p>
          </div>
          <article
            v-for="driver in drivers"
            :key="driver.id"
            class="fleet-driver-card"
          >
            <div class="fleet-card-main">
              <div class="fleet-driver-main">
                <span class="fleet-driver-license"
                  ><UserRound :size="15" />{{ driver.licenseNumber }}</span
                ><strong>{{ driver.fullName }}</strong
                ><span class="fleet-help"
                  >{{ driver.phoneNumber }} ·
                  {{ driver.active ? 'Đang hoạt động' : 'Đã ngừng hoạt động' }}</span
                ><span class="fleet-help">Xe hiện tại: {{ assignedVehicleLabel(driver.id) }}</span>
              </div>
              <div
                v-if="driver.active"
                class="fleet-card-actions"
              >
                <button
                  class="fleet-icon-button"
                  :aria-label="`Sửa tài xế ${driver.fullName}`"
                  @click="fleet.openDriverForm(driver)"
                >
                  <Edit3 :size="15" /></button
                ><button
                  class="fleet-icon-button danger"
                  :aria-label="`Ngừng tài xế ${driver.fullName}`"
                  @click="deactivateDriver = driver"
                >
                  <Trash2 :size="15" />
                </button>
              </div>
            </div></article
        ></template>
        <template v-if="!lockedTab && !fleet.loading && !fleet.error && activeTab === 'trips'"
          ><div
            v-if="trips.length === 0"
            class="fleet-empty"
          >
            <CalendarDays :size="30" />
            <h3>Chưa có chuyến phù hợp</h3>
            <p>Chọn xe, tuyến và giờ xuất phát để lập lịch trình.</p>
          </div>
          <button
            v-for="trip in trips"
            :key="trip.id"
            class="fleet-trip-card"
            :aria-label="`Mở chi tiết chuyến ${trip.id}, ${trip.routeName}`"
            @click="fleet.selectTrip(trip.id)"
          >
            <span class="fleet-trip-title"
              ><strong>#{{ trip.id }} · {{ trip.vehiclePlateNumber }}</strong
              ><span :class="`trip-status ${trip.status.toLowerCase()}`">{{
                TRIP_STATUS_LABELS[trip.status]
              }}</span></span
            ><span class="fleet-trip-route">{{ trip.routeName }}</span
            ><span class="fleet-help"
              >Xuất phát {{ displayTripTime(trip.scheduledDepartureAt) }}</span
            ><span class="fleet-help">Tài xế: {{ trip.driver?.fullName ?? 'Chưa gán' }}</span
            ><span class="fleet-help">Theo lịch: {{ displayTripTime(trip.plannedEndAt) }}</span
            ><ArrowRight
              class="fleet-card-arrow"
              :size="16"
              aria-hidden="true"
            /></button
        ></template>
      </div>
      <div class="fleet-footer fleet-list-footer">
        <button
          v-if="activeTab === 'vehicles'"
          class="btn-primary"
          :disabled="fleet.loading || !!fleet.error"
          @click="fleet.openVehicleForm(null)"
        >
          <Plus :size="16" />Thêm xe mới</button
        ><button
          v-else-if="activeTab === 'drivers'"
          class="btn-primary"
          :disabled="fleet.loading || !!fleet.error"
          @click="fleet.openDriverForm(null)"
        >
          <Plus :size="16" />Thêm tài xế mới</button
        ><button
          v-else
          class="btn-primary"
          :disabled="fleet.loading || !!fleet.error || !hasActiveVehicle"
          @click="fleet.openTripForm"
        >
          <Plus :size="16" />Tạo chuyến mới
        </button>
      </div>
      <p
        v-if="activeTab === 'trips' && !fleet.loading && !hasActiveVehicle"
        class="fleet-prerequisite"
      >
        Thêm ít nhất một xe đang sử dụng ở mục Phương tiện.
      </p>
    </div>
    <VehicleEditor
      v-if="screen.kind === 'vehicle-form'"
      :key="screen.vehicle?.id ?? 'new'"
      :vehicle="screen.vehicle"
      :drivers="fleet.drivers"
      :busy="fleet.busy"
      :error="fleet.error"
      :on-save="saveVehicle"
      :on-close="fleet.close"
    />
    <DriverEditor
      v-if="screen.kind === 'driver-form'"
      :key="screen.driver?.id ?? 'new'"
      :driver="screen.driver"
      :busy="fleet.busy"
      :error="fleet.error"
      :on-save="saveDriver"
      :on-close="fleet.close"
    />
    <TripEditor
      v-if="screen.kind === 'trip-form'"
      :vehicles="fleet.vehicles"
      :drivers="fleet.drivers"
      :initial-vehicle-id="screen.vehicleId"
      :busy="fleet.busy"
      :error="fleet.error"
      :on-save="fleet.saveTrip"
      :on-close="fleet.close"
      :on-manage-routes="onManageRoutes"
    />
    <TripDetailPanel
      v-if="screen.kind === 'trip-detail'"
      :key="`${screen.id}:${fleet.detail?.trip.attemptNumber ?? 'loading'}`"
      :detail="fleet.detail"
      :loading="fleet.loadingDetail"
      :busy="fleet.busy"
      :error="fleet.error"
      :on-close="fleet.close"
      :drivers="fleet.drivers"
      :on-retry="retryTrip"
      :on-action="fleet.transition"
      :on-update-schedule="fleet.updateTripSchedule"
      :on-update-driver="fleet.updateTripDriver"
      :on-delete-trip="fleet.removeTrip"
      :on-focus-stop="onFocusStop"
      :on-simulate="onSimulateTrip"
      :live-snapshot="liveSnapshot"
    />
    <FleetConfirmDialog
      v-if="deactivate"
      :title="`Ngừng sử dụng xe ${deactivate.plateNumber}?`"
      message="Các chuyến chưa kết thúc phải được hoàn thành hoặc hủy trước. Lịch sử xe và chuyến đi vẫn được lưu."
      confirm-label="Xác nhận ngừng sử dụng xe"
      :busy="fleet.busy"
      :error="fleet.error"
      :on-close="() => (deactivate = null)"
      :on-confirm="removeVehicle"
    />
    <FleetConfirmDialog
      v-if="deactivateDriver"
      :title="`Ngừng tài xế ${deactivateDriver.fullName}?`"
      message="Tài xế phải được bỏ gán khỏi xe và các chuyến chưa kết thúc. Lịch sử chuyến đã hoàn thành vẫn được giữ."
      confirm-label="Xác nhận ngừng tài xế"
      :busy="fleet.busy"
      :error="fleet.error"
      :on-close="() => (deactivateDriver = null)"
      :on-confirm="removeDriver"
    />
  </div>
</template>

// vehicletracking-frontend/src/components/fleet/FleetWorkspace.tsx
import { useState } from 'react';
import { BusFront, CalendarDays, CarFront, Edit3, Plus, RefreshCw, Scooter, Search, Trash2 } from 'lucide-react';
import type { FleetVehicle, TripDetail, TripStatus } from '../../types/fleet';
import { TRIP_STATUS_LABELS, vehicleTypeLabel } from '../../types/fleet';
import { useFleetWorkspace } from '../../hooks/useFleetWorkspace';
import { displayTripTime } from '../../utils/tripTime';
import { VehicleEditor } from './VehicleEditor';
import { TripEditor } from './TripEditor';
import { TripDetailPanel } from './TripDetailPanel';
import { FleetConfirmDialog } from './FleetConfirmDialog';
import './fleet.css';
import type { OperationsSnapshot } from '../../types/operations';

export function FleetWorkspace({ onToast, onFocusStop, onManageRoutes, onManageStations, liveSnapshot, onSimulateTrip, onFocusVehicle, tripSelection, onTripCreated }: {
  onToast: (message: string) => void;
  onFocusStop: (position: [number, number], zoom?: number) => void;
  onManageRoutes: () => void; onManageStations: () => void;
  liveSnapshot?: OperationsSnapshot | null; onSimulateTrip?: (id: number) => void; onFocusVehicle?: (id: number) => void;
  tripSelection?: { tripId: number | null } | null; onTripCreated?: (detail: TripDetail) => void;
}) {
  const fleet = useFleetWorkspace(onToast, liveSnapshot, tripSelection, onTripCreated);
  const [query, setQuery] = useState('');
  const [vehicleStatus, setVehicleStatus] = useState<'active' | 'inactive' | 'all'>('active');
  const [tripStatus, setTripStatus] = useState<TripStatus | ''>('');
  const [deactivate, setDeactivate] = useState<FleetVehicle | null>(null);
  const { screen } = fleet;
  const q = query.trim().toLocaleLowerCase('vi');
  const vehicles = fleet.vehicles.filter(vehicle => (vehicleStatus === 'all' || vehicle.active === (vehicleStatus === 'active')) &&
    (!q || `${vehicle.plateNumber} ${vehicle.name}`.toLocaleLowerCase('vi').includes(q)));
  const trips = fleet.trips.filter(trip => (!fleet.vehicleFilter || trip.vehicleId === fleet.vehicleFilter) && (!tripStatus || trip.status === tripStatus) &&
    (!q || `${trip.id} ${trip.vehiclePlateNumber} ${trip.routeName}`.toLocaleLowerCase('vi').includes(q)));
  const filteredVehicle = fleet.vehicles.find(vehicle => vehicle.id === fleet.vehicleFilter);

  return <div className="fleet-workspace">
    <div className="fleet-list-view" hidden={screen.kind !== 'list'}>
      <div className="planning-tabs fleet-tabs" aria-label="Quản lý đội xe">
        <button aria-pressed={fleet.tab === 'vehicles'} onClick={() => { fleet.setTab('vehicles'); setQuery(''); }}><BusFront size={14} />Đội xe <span>{fleet.vehicles.filter(vehicle => vehicle.active).length}</span></button>
        <button aria-pressed={fleet.tab === 'trips'} onClick={() => { fleet.setTab('trips'); setQuery(''); }}><CalendarDays size={14} />Chuyến đi <span>{fleet.trips.length}</span></button>
      </div>
      <div className="fleet-heading"><div><span className="panel-eyebrow">DỮ LIỆU VẬN HÀNH</span><h2>{fleet.tab === 'vehicles' ? 'Danh sách xe' : 'Lịch chuyến đi'}</h2></div>
        <button className="fleet-icon-button" disabled={fleet.loading || fleet.busy} aria-label="Tải lại đội xe và chuyến" onClick={() => void fleet.reload()}><RefreshCw size={16} /></button></div>
      <div className="fleet-list-tools">
        <label className="fleet-search"><Search size={15} /><input aria-label={fleet.tab === 'vehicles' ? 'Tìm xe' : 'Tìm chuyến đi'} placeholder={fleet.tab === 'vehicles' ? 'Biển số hoặc tên xe…' : 'Biển số, tuyến hoặc mã chuyến…'} value={query} onChange={e => setQuery(e.target.value)} /></label>
        {fleet.tab === 'vehicles' ? <select aria-label="Lọc xe" value={vehicleStatus} onChange={e => setVehicleStatus(e.target.value as typeof vehicleStatus)}>
          <option value="active">Đang sử dụng</option><option value="inactive">Đã ngừng sử dụng</option><option value="all">Tất cả xe</option>
        </select> : <>
          <select aria-label="Lọc trạng thái chuyến" value={tripStatus} onChange={e => setTripStatus(e.target.value as TripStatus | '')}>
            <option value="">Mọi trạng thái</option>{Object.entries(TRIP_STATUS_LABELS).map(([id,label]) => <option key={id} value={id}>{label}</option>)}
          </select>
          {fleet.vehicleFilter && <div className="fleet-filter-chip"><span>Xe {filteredVehicle?.plateNumber ?? fleet.vehicleFilter}</span><button onClick={() => fleet.setVehicleFilter(null)}>Bỏ lọc xe</button></div>}
        </>}
      </div>
      <div className="fleet-list-body" aria-busy={fleet.loading}>
        {fleet.loading && <p className="fleet-loading" role="status">Đang tải xe và chuyến đi…</p>}
        {fleet.error && !deactivate && <div className="fleet-error" role="alert">{fleet.error}<button className="fleet-text-button" onClick={() => void fleet.reload()}>Thử lại</button></div>}
        {!fleet.loading && !fleet.error && fleet.tab === 'vehicles' && <>
          {vehicles.length === 0 && <div className="fleet-empty"><BusFront size={30} /><h3>{fleet.vehicles.length ? 'Không tìm thấy xe phù hợp' : 'Chưa có xe trong danh mục'}</h3><p>Thêm xe, sau đó tạo chuyến từ tuyến đã lưu.</p><button className="fleet-text-button" onClick={onManageStations}>Thiết lập trạm</button></div>}
          {vehicles.map(vehicle => <article key={vehicle.id} className="fleet-vehicle-card">
            <div className="fleet-card-main"><button className="fleet-vehicle-select" onClick={() => { setQuery(''); fleet.showVehicleTrips(vehicle.id); }}>
              <span className="fleet-plate">{vehicle.vehicleType === 'MOTORCYCLE' ? <Scooter size={16} /> : <CarFront size={16} />}{vehicle.plateNumber}</span><strong>{vehicle.name}</strong>
              <span className="fleet-help">{vehicleTypeLabel(vehicle.vehicleType)} · {vehicle.active ? 'Đang sử dụng' : 'Đã ngừng sử dụng'} · {liveSnapshot?.positions.some(point => point.vehicleId === vehicle.id) ? 'Đã nhận vị trí' : 'Chưa có vị trí xe'}</span>
            </button>
            {vehicle.active && <div className="fleet-card-actions"><button className="fleet-icon-button" aria-label={`Sửa xe ${vehicle.plateNumber}`} onClick={() => fleet.openVehicleForm(vehicle)}><Edit3 size={15} /></button>
              <button className="fleet-icon-button danger" aria-label={`Ngừng sử dụng xe ${vehicle.plateNumber}`} onClick={() => setDeactivate(vehicle)}><Trash2 size={15} /></button></div>}</div>
            {vehicle.description && <p className="fleet-card-description">{vehicle.description}</p>}
            {liveSnapshot?.positions.some(point => point.vehicleId === vehicle.id) && <button className="fleet-text-button" onClick={() => onFocusVehicle?.(vehicle.id)}>Xem vị trí xe</button>}
            <button className="fleet-text-button" onClick={() => { setQuery(''); fleet.showVehicleTrips(vehicle.id); }}>Xem chuyến đi <span>→</span></button>
          </article>)}
        </>}
        {!fleet.loading && !fleet.error && fleet.tab === 'trips' && <>
          {trips.length === 0 && <div className="fleet-empty"><CalendarDays size={30} /><h3>Chưa có chuyến phù hợp</h3><p>Chọn xe, tuyến và giờ xuất phát để lập lịch trình.</p></div>}
          {trips.map(trip => <button key={trip.id} className="fleet-trip-card" onClick={() => void fleet.selectTrip(trip.id)}>
            <span className="fleet-trip-title"><strong>#{trip.id} · {trip.vehiclePlateNumber}</strong><span className={`trip-status ${trip.status.toLowerCase()}`}>{TRIP_STATUS_LABELS[trip.status]}</span></span>
            <span className="fleet-trip-route">{trip.routeName}</span><span className="fleet-help">Xuất phát {displayTripTime(trip.scheduledDepartureAt)}</span>
            <span className="fleet-help">Theo lịch: {displayTripTime(trip.plannedEndAt)}</span>
          </button>)}
        </>}
      </div>
      <div className="fleet-footer">
        {fleet.tab === 'vehicles' ? <button className="btn-primary" disabled={fleet.loading || !!fleet.error} onClick={() => fleet.openVehicleForm(null)}><Plus size={16} />Thêm xe mới</button>
          : <button className="btn-primary" disabled={fleet.loading || !!fleet.error || !fleet.vehicles.some(vehicle => vehicle.active)} onClick={fleet.openTripForm}><Plus size={16} />Tạo chuyến mới</button>}
      </div>
      {fleet.tab === 'trips' && !fleet.loading && !fleet.vehicles.some(vehicle => vehicle.active) && <p className="fleet-prerequisite">Thêm ít nhất một xe đang sử dụng ở tab Đội xe.</p>}
    </div>
    {screen.kind === 'vehicle-form' && <VehicleEditor key={screen.vehicle?.id ?? 'new'} vehicle={screen.vehicle} busy={fleet.busy} error={fleet.error}
      onSave={async (input, id) => { const saved = await fleet.saveVehicle(input, id); if (saved) { setQuery(''); setVehicleStatus('active'); } return saved; }} onClose={fleet.close} />}
    {screen.kind === 'trip-form' && <TripEditor vehicles={fleet.vehicles} initialVehicleId={screen.vehicleId} busy={fleet.busy} error={fleet.error} onSave={fleet.saveTrip} onClose={fleet.close} onManageRoutes={onManageRoutes} />}
    {screen.kind === 'trip-detail' && <TripDetailPanel key={`${screen.id}:${fleet.detail?.trip.attemptNumber ?? 'loading'}`} detail={fleet.detail} loading={fleet.loadingDetail} busy={fleet.busy} error={fleet.error} onClose={fleet.close}
      onRetry={() => void fleet.selectTrip(screen.id)} onAction={fleet.transition} onUpdateSchedule={fleet.updateTripSchedule} onDeleteTrip={fleet.removeTrip} onFocusStop={onFocusStop} onSimulate={onSimulateTrip} liveSnapshot={liveSnapshot} />}
    {deactivate && <FleetConfirmDialog title={`Ngừng sử dụng xe ${deactivate.plateNumber}?`} message="Các chuyến chưa kết thúc phải được hoàn thành hoặc hủy trước. Lịch sử xe và chuyến đi vẫn được lưu."
      confirmLabel="Xác nhận ngừng sử dụng xe" busy={fleet.busy} error={fleet.error} onClose={() => setDeactivate(null)}
      onConfirm={() => { void fleet.removeVehicle(deactivate).then(success => { if (success) setDeactivate(null); }); }} />}
  </div>;
}
